'''
Usage:
Generates a text file representing the user's Johnny Decimal file system.
File is generated by referencing the JDex.
'''

from env import (jdexFileUseTabs, jdexFileSpacePerTab, jdexFileMarker)

def generateJdexText (tree: list[str]) -> str:
    # expects relative list of file paths, outputs text to be written

    treeSteps = convertFsTree(tree, 'relativeList')

    if jdexFileUseTabs:
        indent = '\t'
    else:
        indent = ' ' * jdexFileSpacePerTab

    output = ''
    for dir in treeSteps:
        tabCount = len(dir) - 1
        output += f'{indent * tabCount}{jdexFileMarker}{dir[-1]}'
        if not dir == treeSteps[-1]:
            output += '\n'

    return output


def saveJdexFile (pathToJdexFile: str, pathToFileSystem: str) -> None:
    # expects full filepaths. Overwrites existing file.

    treeFs = generateFsTree(pathToFileSystem)
    fileText = generateJdexText(treeFs)

    with open(pathToJdexFile, 'w') as f:
        f.write(fileText)

    return


if __name__ == '__main__':
    from development.env import src, jdexFilePath
    from development.sys_utils import generateFsTree, convertFsTree
    from os.path import isfile

    if isfile(jdexFilePath):
        print('Overwriting existing JDex file with updated information.')
    else:
        print('Generating new JDex file.')
    print('JDex File Location:')
    print(jdexFilePath)
    print('JDex Location:')
    print(src)
    saveJdexFile(jdexFilePath, src)
    print('Finished creating new JDex file.')